### ISSUE TITLE
zsh ModuleNotFoundError: No module named 'clipea'

### ISSUE THREAD

**Issue by commadot2** [dave1010/clipea#36]
I'm using zsh, Just installed with `clipea setup` and `clipea alias`
I got:

 ~  ❯ ?? hi
Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "/home/beebeep/.local/pipx/venvs/clipea-cli/lib/python3.11/site-packages/clipea/__main__.py", line 5, in <module>
    from clipea import router
ModuleNotFoundError: No module named 'clipea'

~/.zshrc:
...
alias '??'='source /home/username/.local/pipx/venvs/clipea-cli/lib/python3.11/site-packages/clipea/clipea.zsh'

(`clipea <query>` it works fine)

**Comment by dave1010** [comment]
Hopefully fixed by https://github.com/dave1010/clipea/pull/37

Needs a bit more testing.
